org.gradle.jvmargs=-Xmx4G -Djavax.net.ssl.trustStore=NONE -Djavax.net.ssl.trustStoreType=Windows-ROOT
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=35,36

# 🔥 ANDROID 15 - 16KB Page Alignment Configuration
android.defaults.buildfeatures.buildconfig=true
android.enableR8.fullMode=true
android.bundle.language.enableSplit=false
android.bundle.abi.enableSplit=false
android.bundle.density.enableSplit=false